scrapper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('scrapping/', include('scrapping.urls'))
]

scrapping/urls.py
from django.urls import path
from . import views

app_name = 'scrapping'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:res_id>/', views.detail, name='detail')
]

scrapping/models.py
import datetime

from django.db import models
from math import ceil


class Resolution(models.Model):
    name = models.CharField(max_length=50)
    text = models.CharField(max_length=1000)
    result_text = models.CharField(max_length=200)
    vote_yes = models.IntegerField(default=0)
    vote_no = models.IntegerField(default=0)
    vote_neutral = models.IntegerField(default=0)
    date = models.DateField(default=datetime.date(2020, 1, 1))
    category = models.CharField(max_length=50, default='Category')
    link = models.CharField(max_length=200, default='google.com')

    def voting_result(self):
        quorum = ceil((self.vote_yes + self.vote_no + self.vote_neutral)/2)
        return self.vote_yes >= quorum

    def get_header(self):
        return self.name if len(self.name) <= 60 else f'{self.name[0:60]}...'

    def __str__(self):
        return self.name


class ExtendedResolution(Resolution):
    result = models.BooleanField(default=False)
    result_by_person = models.CharField(max_length=1000, default='')
    attendance = models.CharField(max_length=1000, default='')
    vote_missing = models.IntegerField(default=0)


class Representative(models.Model):
    name = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)
    party = models.CharField(max_length=40)
    #titles_front = models.CharField(max_length=20)
    #titles_back = models.CharField(max_length=20)


class Voting(models.Model):
    option = models.CharField(max_length=20)
    voted_by = models.ForeignKey(Representative, on_delete=models.CASCADE)
    voted_on = models.ForeignKey(ExtendedResolution, on_delete=models.CASCADE)

scrapping/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from scrapping import scrapper

import scrapping.scrapper
from .models import Resolution, Voting, ExtendedResolution


def index(request):
    Resolution.objects.all().delete()
    ExtendedResolution.objects.all().delete()
    scrapper.refresh_data()

    res_list = Resolution.objects.all
    ex_res_list = ExtendedResolution.objects.all
    context = {
        'res_list': res_list,
        'ex_res_list': ex_res_list,
    }
    return render(request, 'index.html', context)


def detail(request, res_id):
    resolution = get_object_or_404(Resolution, pk=res_id)
    return render(request, 'detail.html', {'resolution': resolution})

scrapping/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        table {
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }

        td, th {
          border: 1px solid #dddddd;
          text-align: left;
          padding: 8px;
        }

        tr:nth-child(even) {
          background-color: #dddddd;
        }
    </style>
</head>
<body>
    <h1>{{ resolution.name }}</h1>
    <p>{{ resolution.text }}</p>
    <br>
    <p>{{ resolution.result_text }}</p>
    <h2>Výsledky</h2>
    <table style="width:100%">
      <tr>
        <th>Ano</th>
        <th>Ne</th>
        <th>Zdržel se</th>
      </tr>
      <tr>
        <td>{{ resolution.vote_yes }}</td>
        <td>{{ resolution.vote_no }}</td>
        <td>{{ resolution.vote_neutral }}</td>
      </tr>
    </table>

    <h2>Schváleno:
        {% if resolution.voting_result %}
            ANO
        {% else %}
            NE
        {% endif %}
    </h2>

</body>
</html>

scrapping/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello </title>
</head>
<body>
{% if name  %}
<h1>Hello {{name}}</h1>
{% else %}
<h1>Hello nejmenovaný</h1>
{% endif %}
</body>
</html>

scrapping/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Bare - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <!--link href="css/styles.css" rel="stylesheet" /-->
        {% load bootstrap5 %}

        {# Load CSS and JavaScript #}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Link</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            <div class="text-center mt-5">
                <h1>PDF Scrapper</h1>
                <p class="lead">Návrhy z Rady města Nová Role v přehlednější formě</p>
                <p>v0.1</p>
            </div>
        </div>

        <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">

            {% if ex_res_list %}
                {% for eres in ex_res_list %}
                    <div class="card">
                    <div class="card-header btn" data-bs-toggle="collapse" data-bs-target="#collapseEx{{ forloop.counter }}">
                      <a class="btn float-start">{{ eres.get_header }}
                          {% if eres.result %}
                          ✅
                          {% else %}
                          ❌
                          {% endif %}
                      </a>
                      <button type="button" class="btn btn-light float-end" disabled>{{ res.category}}</button>
                    </div>

                    <div id="collapseEx{{ forloop.counter }}"  class="collapse">
                      <div class="card-body">
                          <p>
                              {{ eres.text }}
                          </p>
                          <button type="button" class="btn btn-secondary" disabled>
                              Pro: {{ eres.vote_yes }}  Proti: {{ eres.vote_no }}
                              {% if eres.vote_neutral > 0 %}
                              Zdržel se: {{ eres.vote_neutral}}
                              {% endif %}
                          </button>
                           {% if eres.result == True %}
                                <button type="button" class="btn btn-success" disabled>Přijato</button>
                           {% else %}
                                <button type="button" class="btn btn-danger" disabled>Nepřijato</button>
                           {% endif %}


                          <div class="card-header btn" data-bs-toggle="collapse" data-bs-target="#collapseExRes{{ forloop.counter }}">
                            Podrobné výsledky hlasování
                          </div>
                          <div id="collapseExRes{{ forloop.counter }}"  class="collapse">
                            <div class="card-body">
                                <p>{{ eres.result_by_person }} </p>


                            </div>
                          </div>




                        <button type="button" class="btn btn-info float-end" href="{{ res.source_link}}" disabled>Zdroj</button>
                        <button type="button" class="btn btn-light float-end" disabled>{{ res.date}}</button>
                      </div>
                    </div>
                  </div>
                {% endfor %}
            {% endif %}



            </div>
        <div class="col-sm-1"></div>
    </div>

        <-- Rada--*>
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-10">

                {% if res_list %}
                    {% for res in res_list %}
                        <div class="card">
                        <div class="card-header btn" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}">
                          <a class="btn float-start">{{ res.get_header }}
                              {% if res.voting_result %}
                              ✅
                              {% else %}
                              ❌
                              {% endif %}
                          </a>
                          <button type="button" class="btn btn-light float-end" disabled>{{ res.category}}</button>
                        </div>

                        <div id="collapse{{ forloop.counter }}"  class="collapse">
                          <div class="card-body">
                              <p>
                                  {{ res.text }}
                              </p>
                              <button type="button" class="btn btn-secondary" disabled>
                                  Pro: {{ res.vote_yes }}  Proti: {{ res.vote_no }}
                                  {% if res.vote_neutral > 0 %}
                                  Zdržel se: {{ res.vote_neutral}}
                                  {% endif %}
                              </button>
                               {% if res.voting_result %}
                                    <button type="button" class="btn btn-success" disabled>Přijato</button>
                               {% else %}
                                    <button type="button" class="btn btn-danger" disabled>Nepřijato</button>
                               {% endif %}

                            <button type="button" class="btn btn-info float-end" href="{{ res.source_link}}" disabled>Zdroj</button>
                            <button type="button" class="btn btn-light float-end" disabled>{{ res.date}}</button>
                          </div>
                        </div>
                      </div>
                    {% endfor %}
                {% endif %}



                </div>
            <div class="col-sm-1"></div>
        </div>

    </body>
</html>

scrapping/templates/indexOld.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My test page</title>
  </head>
  <body>

    {% if res_list %}
        <ul>
        {% for res in res_list %}
            <li><a href="{% url 'scrapping:detail' res.id %}">{{ res.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No resolutions are available.</p>
    {% endif %}

  </body>
</html>